### ISSUE TITLE
Power bi reports not rendering due to third party cookies getting blocked because of new Chrome update

### ISSUE THREAD

**Issue by Klaus-8** [microsoft/powerbi-client-react#112]
Due to a recent Chrome update all the third party cookies are getting blocked which is preventing the network request to trigger responsible for fetching power bi report details which is resulting in report not getting rendered. 
Please refer below screenshots for more details.

Console warning :
![image](https://github.com/microsoft/powerbi-client-react/assets/97245667/09e7ecfa-192c-47bc-8563-c0b73b0d0635)

Issues tab details :
![image](https://github.com/microsoft/powerbi-client-react/assets/97245667/d285ef11-6672-4870-8426-db2998e3cb96)

Cookies Warning message in network tab :
![image](https://github.com/microsoft/powerbi-client-react/assets/97245667/5dd08a56-d89d-4a9e-aff3-9f94bff4d010)

Warning message in Application tab of console :
![image](https://github.com/microsoft/powerbi-client-react/assets/97245667/7dfc9457-eb70-4a09-9052-424f88c2e8a8)

Any help will much appreciated.

**Comment by v-MadhavC** [comment]
Hi, we tried reproducing the issue and we observed that we are getting the same warning message but since it is just a warning, we were still able to embed the report and the report rendered correctly.
Here is the snapshot for your reference:
![image](https://github.com/microsoft/powerbi-client-react/assets/126773262/c225bfc2-e84d-41ba-aee1-e57d80346344)
Could you tell us whether you are facing this issue specifically with Chrome? And also, are you able to embed the report in Microsoft Edge?

**Comment by Klaus-8** [comment]
Hi Madhav

Thanks for your reply. 
At first we thought the reports are not rendering due to the cookie warnings but the real reason in our case was due to the invalid AAD token generated which was passed in the Power BI embed react component. We have fixed that issue and now the report are rendering correctly.
