### ISSUE TITLE
EventHandlers are only updated if their code changes

### ISSUE THREAD

**Issue by voroshkov** [microsoft/powerbi-client-react#113]
If `eventHandlers` prop **reference** changes, but the code of the `eventHandlers` Map remains the same - then event handlers won't be updated in the `PowerBIEmbed` React component. 

This makes it impossible to store the report instance in a React component state and refer to this instance in the event handler like this:

```js
export const MyComponent: React.FC<MyComponentProps> = () => {
  const [report, setReport] = useState<Report>();

  const handleVisualClick: EventHandler = (event) => {
    // here I'd like to get the Visual object and manipulate it, but cannot do it using the `report` variable
    console.log('report', report); // will always log "undefined"
  };

  const embedConfig = {
    //...
  };

  const eventHandlers = new Map([['visualClicked', handleVisualClick]]);

  return (
    <PowerBIEmbed
      embedConfig={embedConfig}
      eventHandlers={eventHandlers}
      getEmbeddedComponent={(embedObject: Embed) => {
        setReport(embedObject as Report);
      }}
    />
  );
};
```
There's a workaround, but it's not the React way of doing things:
```js
  const handleVisualClick: EventHandler = (event) => {
    // workaround is to use something like:
    const reportGlobal = window.powerbi.get(event.target as HTMLElement) as Report;
    console.log('report', reportGlobal); // will log the report object
  };
```

It happens because of the following code in setEventHandlers private method of PowerBIEmbed component:
```js
		const eventHandlerMapString = stringifyMap(this.props.eventHandlers);

		// Check if event handler map changed
		if (this.prevEventHandlerMapString === eventHandlerMapString) {
			return;
		}
```
Direct link: https://github.com/microsoft/powerbi-client-react/blob/d9d06a61d9b7707daaa16f925dae9b831bf4bf55/React/powerbi-client-react/src/PowerBIEmbed.tsx#L285

**Comment by v-MadhavC** [comment]
We implemented the code snippet provided by you and were able to reproduce the issue. 
To resolve the issue of report instance coming out to be 'undefined', you need to define eventHandlers as a state and then pass it as a prop to the powerBIEmbed component. 
By defining 'eventHandlers' as a state and then passing it as a prop, you ensure that when the contents of the event handlers change, it will detect the change because you're providing a new reference to the Map when you call 'setEventHandlers(newMap)'. This triggers a re-render of the component with the updated event handlers.

Please refer to the following code snippet:
```
const [eventHandlers, setEventHandlers] = useState(new Map());

const handleVisualClick = (event) => {
		console.log('report', report);
	};

return (
	<PowerBIEmbed
	   embedConfig={embedConfig}
	   eventHandlers={eventHandlers}
	   getEmbeddedComponent={(embedObject: Embed) => {
			setReport(embedObject as Report);
	   }}
	/>
);
```

**Comment by voroshkov** [comment]
Sorry, I don't get it. Your example doesn't seem to use the defined `handleVisualClick`.
Could you provide a fully working example where `report` stored in state can be used within the EventHandler?

**Comment by v-MadhavC** [comment]
React state updates are asynchronous and do not immediately reflect the new state. Functions rely on the current closure's state values, and state updates will only be visible in the next re-render. This means the existing closures remain unchanged, and new closures are created for subsequent renders.



To access the report state inside the visualClicked event handler, you just need to pass the report state to the event handler.



Code snippet:
```
function DemoApp (): JSX.Element {

// PowerBI Report object (to be received via callback)

   const [report, setReport] = useState<Report>();



   const embedConfig = {

       //...

   };



   const[eventHandlersMap, setEventHandlersMap] = 

   useState<Map<string, (event?: service.ICustomEvent<any>, embeddedEntity?: Embed) => void | null>>(new Map([

       ['visualClicked', (report) => {

           console.log('visual clicked');

           console.log("report", report);

         }     

       ]

   ]));



   const reportComponent =

       <PowerBIEmbed

           embedConfig = { sampleReportConfig }

           eventHandlers = { eventHandlersMap }

           cssClassName = { reportClass }

           getEmbeddedComponent = { (embedObject: Embed) => {

               console.log(`Embedded object of type "${ embedObject.embedtype }" received`);

               setReport(embedObject as Report);

           } }

       />;

}
```

Console:
![image](https://github.com/microsoft/powerbi-client-react/assets/126773262/e7d58a8e-9e57-4089-b5c5-9ec1567cb219)

**Comment by voroshkov** [comment]
Oh, no... You can't be serious, because your code logs the ICustomEvent object as "report" and it cannot produce the output you provided.

I replicated your code locally and got the following in the console:

![image](https://github.com/microsoft/powerbi-client-react/assets/8790856/bd4aca76-ef3d-49d9-83cf-6310297af8b1)

Here is my code, which is exactly yours, but appended with actual config info retrieval:

```js
import { useState } from 'react';
import { EmbedProps, EmbedType, PowerBIEmbed } from 'powerbi-client-react';
import { Embed, models, service } from 'powerbi-client';
import { useQuery } from '@tanstack/react-query';
import { useUuiContext } from '@epam/uui-core';
import { TApi } from '../../../api/apiDefinition';

export function TestPageMs(): JSX.Element | string {
  const { api } = useUuiContext<TApi>();

  const [report, setReport] = useState<Report>();
  const queryKey = ['embedInfo'];

  const getEmbedInfo = useQuery({ queryKey: queryKey, queryFn: api.getPowerBiReportEmbedInfo });

  const [eventHandlersMap, setEventHandlersMap] = useState<
    Map<string, (event?: service.ICustomEvent<any>, embeddedEntity?: Embed) => void | null>
  >(
    new Map([
      [
        'visualClicked',
        (report) => {
          console.log('visual clicked');

          console.log('report', report);
        },
      ],
    ]),
  );

  if (getEmbedInfo.isError) return 'Error';
  if (getEmbedInfo.isPending) return 'Loading';

  const {
    embedUrl: { embedUrl, reportId },
    accessToken,
  } = getEmbedInfo.data;

  const embedConfig: EmbedProps['embedConfig'] = {
    id: reportId,
    type: EmbedType.Report,
    embedUrl: embedUrl,
    tokenType: models.TokenType.Embed,
    accessToken: accessToken,
    settings: {
      navContentPaneEnabled: true,
    },
  };

  const reportComponent = (
    <PowerBIEmbed
      embedConfig={embedConfig}
      eventHandlers={eventHandlersMap}
      getEmbeddedComponent={(embedObject: Embed) => {
        console.log(`Embedded object of type "${embedObject.embedtype}" received`);

        setReport(embedObject as Report);
      }}
    />
  );

  return reportComponent;
}
```

**Comment by v-MadhavC** [comment]
Sorry for the confusion, you can refer the updated code for accessing the report inside eventHandler. Please feel free to reach out if you have any queries related to this.

**Comment by voroshkov** [comment]
Well, this is a hack... 
If we talk about workarounds, you can also get the report via global powerbi object:

```js
export const getReportForEventHandler = (event: service.ICustomEvent<any>): Report | undefined => {
  if (!event.target) return;
  return window.powerbi.get(event.target as HTMLElement) as Report;
};
```

Still I'd say this remains confusing for React developers. Probably stringifying the event handlers for comparison is not a good way of doing things? (see my 1st post in this thread)

**Comment by KotanaSai21** [comment]
@uvujosevic ,  please look into my response.

We're setting the Event Handlers during the component mounting phase. Only when the Event handlers is changed, we're setting the event handlers again. We will look into your comment on stringifying and compare the eventHandlers. But the motive is not to set same event Handlers twice.

Here the issue is with the code where we're using the `useState` hook to set the Report object. When 
the report object is updated, it's not getting updated inside the handleClick function which is getting called from the 'visualClicked' event Handler that is set during the mounting phase. (If we call the handleClick function separately from somewhere in the code report is not undefined but when visualClicked event triggered and invoking handleClicked function from therereport object is undefined.)

**Approach 1:** 
Use the `useRef` to declare the report object and assign the value getting from callback. Please find the below updated code. This is better way to declare a variable if we use it inside the functions which will be triggered by the events. Whenever the report variable gets updated, it will also update the same in handleClick function (triggered from visualClicked).

```
const reportRef  =  useRef<Report>();

const handleVisualClick = () => {
	console.log('report', report); // will always log "undefined"
	console.log('reportRef', reportRef.current); // will log the report object"
};

const[eventHandlersMap, setEventHandlersMap] = useState<Map<string, (event?: service.ICustomEvent<any>, embeddedEntity?: Embed) => void | null>>(new Map([
	['loaded', () => console.log('Report has loaded')],
	['rendered', () => console.log('Report has rendered')],
	['error', (event?: service.ICustomEvent<any>) => {
			if (event) {
				console.error(event.detail);
			}
		},
	],
	['visualClicked', () => handleVisualClick()],
	['pageChanged', (event) => console.log(event)],
]));

const reportComponent =
	<PowerBIEmbed
		embedConfig = { sampleReportConfig }
		eventHandlers = { eventHandlersMap }
		cssClassName = { reportClass }
		getEmbeddedComponent = { (embedObject: Embed) => {
			console.log(`Embedded object of type "${ embedObject.embedtype }" received`);
			reportRef.current = embedObject as Report;
		} }
	/>;
```

**Approach 2:** 
Set the Visual Clicked event once the Report gets loaded, so the report object is not undefined. 
After report gets embedded, place this code to set the Visual Clicked event.
```
setEventHandlersMap(new Map<string, (event?: service.ICustomEvent<any>, embeddedEntity?: Embed) => void | null> ([
        ['visualClicked', () => {handleVisualClick();}],
 ]));
```
 
It's not a hack and instead the way of defining variables in React with `useRef` instead `useState`.
Please let me know if you have questions with the approaches.

**Comment by JANA-itsaishvili** [comment]
I'm having a similar issue. I am passing an array of 2 events, error and buttonClicked, where buttonClicked depends on a reactive value hubConnected -- which is a boolean indicated connection state with the SignalR backend. The component is updated correctly on this state change, but the event listeners seem to be memoized after the report has loaded/rendered. 

The embedded component forms a stale closure on the initial render value, rather than on the latest.

The easiest way to resolve this, which is not ideal is with a key to force PowerBIEmbed to rerender.

Map also feels like an overkill for mapping string keys to functions. Why not use a regular object instead of this `[["event", () => void]]`?

Anyway, please look into not memoizing event handlers, or fix your dependency arrays.

**Comment by v-MadhavC** [comment]
Event handlers defined during the initial render(component mounting phase) capture the state as it was at that time. In your case, updates to the hubConnected state do not automatically recreate the eventHandlersMap because we aim to avoid setting the same event handlers repeatedly, which could lead to redundant operations. To ensure that event handlers always have the latest state value, we recommend using `useRef` hook to hold a reference to the latest state.

**Comment by ayeshurun** [comment]
The recommend approach is using the `useRef` hook. Please continue to share your feedback and get support through these channels:

- **Feature Requests**: Submit your ideas and suggestions to the [Fabric Ideas Portal](https://ideas.fabric.microsoft.com/), where you can also vote on ideas from other developers.
- **Bug Reports and Technical Assistance**: Visit the [Fabric Developer Community Forum](https://community.fabric.microsoft.com/t5/Developer/bd-p/Developer). Our team and community experts are ready to assist you.
- **Additional Support**: Contact your account manager or reach out to the [Fabric Support Team](https://support.fabric.microsoft.com/en-us/support/).
