### ISSUE TITLE
The demo does not work properly

### ISSUE THREAD

**Issue by JinHe-PerkinElmer** [microsoft/powerbi-client-react#117]
The demo does not work properly. It seems that the report has been removed.
Is there any alternative? We are planning to integrate Power BI and need a demo.
The API error is as follows:
```
Request URL: https://aka.ms/CaptureViewsReportEmbedConfig
Request Method: GET
Status Code: 301 Moved Permanently
```
```
Request URL: https://playgroundbe-bck-1.azurewebsites.net/Reports/SampleReport
Request Method: GET
Status Code: 403 Site Disabled
```

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. We identified the root cause of the issue and will add it to our backlog.

Follow below steps as a workaround:
1. Remove the selected code from the `embedReport` method as shown in the screenshot.
	
![image](https://github.com/user-attachments/assets/fa6de3fb-afb9-4f86-a8bb-13f77d5ef04e)


2. Update the "accessToken" and "embedUrl" in the `setReportConfig` to embed the report as shown in the image below.
	
![image](https://github.com/user-attachments/assets/8b749e1d-a777-45c0-8fcd-070288d4788a)

	
To generate the access token, use the following REST API: [Embed Token - Generate Token - REST API (Power BI Power BI REST APIs) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/power-bi/embed-token/generate-token)
	To generate the embed token, use the following REST API: [Reports - Get Report In Group - REST API (Power BI Power BI REST APIs) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-report-in-group?tryIt=true&source=docs#code-try-0)
