### ISSUE TITLE
how do you use hooks with eventHandlersMap?

### ISSUE THREAD

**Issue by andy-dev** [microsoft/powerbi-client-react#30]
Hello, I set an interval that refreshes the powerBi report after X amount of seconds.
Is there a way to use a reactHook to set state every-time the report renders. Counter will show zero. 

```
     const [counter, setCounter] = useState(0);
    
       const updateCounter = () => {
       console.log("counter", counter);
         setCounter(counter + 1);
       };
    
       const handleRender = () => {
         updateCounter();
       };
    
       const eventHandlersMap = new Map([
         [
          "loaded",
          function() {
            console.log("Report has loaded");
          }
        ],
        [
          "rendered",
          function() {
            console.log("Report has rendered");
            handleRender();
         }
       ],
```

**Comment by anant-k-singh** [comment]
The new event handlers map is only applied when it is changed. In your case, the event handler map is set once in the beginning.
Due to [Closures in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures), the old value of `counter` is used when your `handleRender()` method in invoked inside 'rendered' event handler.

Alternately, you can use the `useRef` hook here.
```js
const counter = useRef(0);
const updateCounter = () => {
  console.log("counter", counter);
  setCounter(counter + 1);
};
```
