### ISSUE TITLE
Power Bi Action Bar Not Showing Export

### ISSUE THREAD

**Issue by coderdark** [microsoft/powerbi-client-react#56]
Hi, I am trying to embed a report using powerbi-client-react and i am setting `bars.actionBar.visible to true`.   I get a action bar but I am not able to get the export option.   Below is a code that I am running on the power bi sandbox.    

Is this a bug with the react component?  I am trying to get the action bar with the options presented from this docs: https://docs.microsoft.com/en-us/javascript/api/overview/powerbi/embed-for-organization. Has anyone successfully got this to work?

Using 
"react": "^16.10.2"
"powerbi-client-reactt":"^1.3.3"

Code

```
let loadedResolve, reportLoaded = new Promise((res, rej) => { loadedResolve = res; });
let renderedResolve, reportRendered = new Promise((res, rej) => { renderedResolve = res; });

// Get models. models contains enums that can be used.
models = window['powerbi-client'].models;

// Embed a Power BI report in the given HTML element with the given configurations
// Read more about how to embed a Power BI report in your application here: https://go.microsoft.com/fwlink/?linkid=2153590
function embedPowerBIReport() {
    // Read embed application token
    let accessToken = EMBED_ACCESS_TOKEN;

    // Read embed URL
    let embedUrl = EMBED_URL;

    // Read report Id
    let embedReportId = REPORT_ID;

    // Read embed type from radio
    let tokenType = TOKEN_TYPE;

    // We give All permissions to demonstrate switching between View and Edit mode and saving report.
    let permissions = models.Permissions.All;

    // Create the embed configuration object for the report
    // For more information see https://go.microsoft.com/fwlink/?linkid=2153590
    let config = {
        type: 'report',
        tokenType: tokenType == '0' ? models.TokenType.Aad : models.TokenType.Embed,
        accessToken: accessToken,
        embedUrl: embedUrl,
        id: embedReportId,
        permissions: permissions,
        viewMode: models.ViewMode.Edit,
        settings: {
            bars:{
                actionBar:{
                    visible:true
                }
            },
            panes: {
                filters: {
                    visible: false
                },
                pageNavigation: {
                    visible: false
                }
            }
        }
    };

    // Get a reference to the embedded report HTML element
    let embedContainer = $('#embedContainer')[0];

    // Embed the report and display it within the div container.
    report = powerbi.embed(embedContainer, config);

    // report.off removes all event handlers for a specific event
    report.off("loaded");

    // report.on will add an event handler
    report.on("loaded", function () {
        loadedResolve();
        report.off("loaded");
    });

    // report.off removes all event handlers for a specific event
    report.off("error");

    report.on("error", function (event) {
        console.log(event.detail);
    });

    // report.off removes all event handlers for a specific event
    report.off("rendered");

    // report.on will add an event handler
    report.on("rendered", function () {
        renderedResolve();
        report.off("rendered");
    });
}

embedPowerBIReport();
await reportLoaded;

// Insert here the code you want to run after the report is loaded

await reportRendered;

// Insert here the code you want to run after the report is rendered

```

**Comment by LevinGar** [comment]
Besides the configuration of the embedded component, there is a set of functionalities that are allowed only from the Azure Active Directory App that handles the embedded service and set from the BI admin portal.
One easy way to see if your service is allowed to export is by opening the options of the visual objects you have when the report is embedded, if you do not see any option is because there are some configurations you have to do before trying to show these export options on the client-side.

Tenant settings that control the availability of features in the Power BI user interface can help to establish governance policies, but they're not a security measure. For example, the Export data setting doesn't restrict the permissions of a Power BI user on a dataset. Power BI users with read access to a dataset have the permission to query this dataset and might be able to persist the results without using the Export data feature in the Power BI user interface.
In these links, you can find some useful information of the different configurations you have to do:
https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#export-and-sharing-settings
https://docs.microsoft.com/en-us/rest/api/power-bi/reports/export-to-file
https://blog.jpries.com/2020/01/25/power-bi-granting-permission-to-a-custom-application-in-azure-active-directory-app-registration/

Make sure your AAD application has all the necessary  permissions to access the power BI API.
I have checked the code you have to show the embedded report and it is ok, I would recommend you to check the additional configurations and permissions you need to do what you want to do in the Azure Active Directory Application and the Power BI admin platform before you continue working on the client-side.
