### ISSUE TITLE
Page navigation does not update scroll location to top of the page

### ISSUE THREAD

**Issue by vivian-hua** [microsoft/powerbi-client-react#57]
- On a report page that has a vertical scrollbar, scroll towards middle/bottom of the report page
- Call setPage (or use navigation pane) to navigate to a new report page
- See that the scroll location is the same as the previous page rather than at the top

**Comment by Guy-Moses** [comment]
(Issue tracked internally)
This issue is not related to this repo - closing.
If you arrived here looking for a solution, maybe check this [post](https://community.powerbi.com/t5/Service/Page-navigation-opening-report-in-middle-of-the-page/m-p/1698832) in MIcrosoft Power BI community forum. A the point of writing there's still no answer there, but it'll get updated once there is one.

**Comment by Guy-Moses** [comment]
Note: If you arrived here looking for a solution, maybe check this [post](https://community.powerbi.com/t5/Service/Page-navigation-opening-report-in-middle-of-the-page/m-p/1698832) in MIcrosoft Power BI community forum. At the point of writing there's still no answer there, but it'll get updated once there is one.
Also, if you have additional details about this issue, consider sharing them there.
