### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by mcdowellalex** [microsoft/powerbi-client-react#65]
Whenever trying to build, the error `ReferenceError: window is not defined` comes up. Now, this is actually in [powerbi-client](https://github.com/Microsoft/PowerBI-JavaScript), not powerbi-client-react, but I can't raise an issue there, and I am also using powerbi-client-react as well since it's a Gatsby (or NextJS project potentially).

But, in the powerbi-client code there should be the following where the instances of window are used
```js
if (typeof window !== 'undefined') {
  console.log('You are on the browser')
  // ✅ Can use window here
} else {
  console.log('You are on the server')
  // ⛔️ Don't use window here
}
```

**Comment by benjamin-musil** [comment]
Just ran into this issue myself when trying to use Next! Also stumbled upon the workaround thread that @mcdowellalex was also in, link here if anyone else sees this issue and needs a workaround solution with Next: https://github.com/microsoft/powerbi-client-react/issues/28#issuecomment-1074409428

**Comment by benjamin-musil** [comment]
I had to do one more tinker, and that was to fully turn off SSR to the dashboard component. In the linked issue, a user suggested:

```js
const DynamicDashboard = dynamic(() =>
    import('../components/dashboard/dynamicDashboard').then((dashboard) => dashboard.default),
  );
```

Which led to the `window is not defined` error happening only *every other* refresh now instead of all the time (because of SSR trying to store this component). I fully resolved the issue by turning off SSR for this component, which is just adding an argument to the above snippet:

```js
const DynamicDashboard = dynamic(() =>
    import('../components/dashboard/dynamicDashboard').then((dashboard) => dashboard.default),
    { ssr: false }
  );
```

But this totally destroys the point of having SSR benefits with Next, so this is very much an issue still.

**Comment by kkd1215** [comment]
Hi there, 

Thanks for reaching out! We understand that you are experiencing an error due to the absence of the window object, which is not available in server-side rendering.

We have the following 2 options to resolve this issue:

Option 1: Check if the window object exists before using it in the code. However, this approach may require to skip code that relies on the window object, which may not be ideal for our use case.

Option 2: Use dynamic imports or lazy loading to only load the code that uses the window object on the client-side. This approach ensures that the code is executed only in the browser, where the window object is available, without requiring to skip any code.

You can try the following code for using dynamic importing:
`import dynamic from 'next/dynamic'`
`import { EmbedProps } from 'powerbi-client-react';`
`import { models } from "powerbi-client";`
`const PowerBIEmbed = dynamic<EmbedProps>(() => import('powerbi-client-react').then(m => m.PowerBIEmbed), { ssr: false });`

Please let us know if you need any further assistance or clarification.
Thank you for bringing this to our attention. We appreciate your feedback and support.

**Comment by FELIPEPPEGORARO** [comment]
ainda estou tendo o problema de window is not defined, mesmo após todas as dicas dinamicas mencionadas acima.

Meu código abaixo:

import React from 'react';
import { NextPage } from 'next';
import { models } from 'powerbi-client';
import Head from 'next/head';
import styles from '../../../styles/powerbi.module.scss';
import {PowerBIEmbed} from 'powerbi-client-react';



const DynamicDashboard: NextPage = () => {

  const storageTokenData = sessionStorage.getItem('tokenData');
  const tokenData = storageTokenData ? JSON.parse(storageTokenData) : null;
  console.log(tokenData);
  return (
  <>    
      <Head>
        <title>Indicadores de Desempenho</title>
      </Head>


      <div className={styles.pbiContainer}>
              <PowerBIEmbed
                embedConfig={{
                  type: 'report',
                  id: tokenData.reportId,
                  embedUrl: tokenData.embedUrl,
                  accessToken: tokenData.accessToken,
                  tokenType: models.TokenType.Embed,
                  settings: {
                    panes: {
                      filters: {
                        expanded: false,
                        visible: false,
                      },
                    },
                    background: models.BackgroundType.Transparent,
                  },
                }}
                cssClassName={styles.pbiContainer}

              />
      </div>
    </>
  );
}

export default DynamicDashboard;

-----------------------------
import dynamic from 'next/dynamic';
import { NextPage } from 'next';
import '../powerbi/dynamicPbi';


const Dashboard: NextPage = () => {
  const DynamicDashboard = dynamic(() =>
    import('../powerbi/dynamicPbi').then((dashboard) => dashboard.default),
    {ssr:false}
  );

  return (
    <>
        <DynamicDashboard />
    </>
  );
};

export default Dashboard;
